apiVersion: v1
kind: Service
metadata:
  name: internal-router
  labels:
    app: internal-router
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: internal-router
  type: ClusterIP