apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-router
spec:
  selector:
    matchLabels:
      app: internal-router
  replicas: 3
  template:
    metadata:
      labels:
        app: internal-router
    spec:
      containers:
        - name: nginx
          image: nginx:1.23-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/templates
              readOnly: false
              name: internal-router-config
            - mountPath: /var/log/nginx
              name: log
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            httpGet:
              port: http
              path: /
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
            httpGet:
              port: http
              path: /
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "2"
      volumes:
        - name: internal-router-config
          configMap:
            name: internal-router-config
            items:
              - key: default.conf.template
                path: default.conf.template
        - name: log
          emptyDir: { }