version: "2"
run:
  concurrency: 4
  go: "1.25"
  issues-exit-code: 1
linters:
  default: none
  enable:
    - goconst
    - gocyclo
    - goprintffuncname
    - misspell
    - nakedret
    - unconvert
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocyclo:
      min-complexity: 20
    nakedret:
      max-func-lines: 0
    nonamedreturns:
      report-error-in-defer: true      
  exclusions:
    generated: lax
    presets:
      - comments 
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: _test\.go      
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
