apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-argocd-agent
subjects:
  - kind: ServiceAccount
    name: cf-argocd-agent
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-agent-cm
data:
  host: https://argocd-server
  integration: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
spec:
  selector:
    matchLabels:
      app: cf-argocd-agent
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cf-argocd-agent
    spec:
      serviceAccountName: cf-argocd-agent
      containers:
        - env:
            - name: AGENT_VERSION
              value: "1.72.3"
            - name: ARGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: argocd-agent-cm
                  key: host
            - name: ARGO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-token
                  key: token
            - name: ENV_NAME
              value: kubernetes
            - name: CODEFRESH_HOST
              value: https://g.codefresh.io
            - name: CODEFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cf-argocd-agent
                  key: token
            - name: IN_CLUSTER
              value: "true"
            - name: CREATE_INTEGRATION_IF_NOT_EXIST
              value: "true"
            - name: MASTERURL
              value: ""
            - name: SYNC_MODE
              value: "CONTINUE_SYNC"
            - name: APPLICATIONS_FOR_SYNC
              value: ""
            - name: CODEFRESH_INTEGRATION
              valueFrom:
                configMapKeyRef:
                  name: argocd-agent-cm
                  key: integration
            - name: CODEFRESH_GIT_INTEGRATION
              value: github
          image: codefresh/argocd-agent:stable
          imagePullPolicy: Always
          name: cf-argocd-agent
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.4"
            limits:
              memory: "512Mi"
              cpu: "0.8"
      restartPolicy: Always
