apiVersion: v1
kind: Service
metadata:
  labels:
    app: cap-app-proxy
  name: cap-app-proxy
spec:
  ports:
    - name: web
      port: 2746
      protocol: TCP
      targetPort: 2746
  selector:
    app: cap-app-proxy
