apiVersion: v1
kind: Service
metadata:
  labels:
    app: cap-app-proxy
  name: cap-app-proxy
spec:
  selector:
    app: cap-app-proxy
  ports:
    - name: http
      port: 3017
      protocol: TCP
      targetPort: http
