apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cap-app-proxy
  name: cap-app-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cap-app-proxy
subjects:
  - kind: ServiceAccount
    name: cap-app-proxy
