apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: codefresh-eventbus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  nats:
    native:
      replicas: 3
      auth: token
      containerTemplate: {}
