apiVersion: batch/v1
kind: Job
metadata:
  name: csdp-add-cluster-job
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600  # stick around for 10m
  template:
    metadata:
      name: csdp-add-cluster-pod
    spec:
      serviceAccount: argocd-manager
      restartPolicy: Never
      containers:
        - name: main
          image: quay.io/codefresh/csdp-add-cluster:latest
          imagePullPolicy: Always
          command:
            - bash
          args:
            - ./add-cluster.sh
          env:
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: INGRESS_URL
              valueFrom:
                configMapKeyRef:
                  name: csdp-add-cluster-cm
                  key: ingressUrl
            - name: CSDP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: csdp-add-cluster-secret
                  key: csdpToken
            - name: CONTEXT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csdp-add-cluster-cm
                  key: contextName
            - name: SERVER
              valueFrom:
                configMapKeyRef:
                  name: csdp-add-cluster-cm
                  key: server
            - name: CSDP_TOKEN_SECRET
              value: $(CSDP_ADD_CLUSTER_SECRET)
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 256Mi
              cpu: '0.2'
