apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.0.2/install.yaml
patches:
  - patch: |-
      - op: remove
        path: /spec/preserveUnknownFields
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
