apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/codefresh-io/argo-cd/release-2.1/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/applicationset/master/manifests/install.yaml?ref=2c62537a8e5a # TODO: switch to the next release when available
  - default-rbac.yaml
images:
  - name: quay.io/codefresh/argocd
    newName: quay.io/codefresh/argocd
    newTag: v2.1.14-cap-CR-rev-logs

# will be effective on argo-cd 2.1
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=20s"
      - "accounts.admin=apiKey,login" # need to be able to generate apikey for generic eventsource
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - "server.insecure=true"

patches:
  # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default

  - path: argocd-resources.argocd-application-controller.jsonpatch.yaml
    target:
      name: argocd-application-controller
      kind: StatefulSet
      group: apps
      version: v1
  - path: argocd-resources.argocd-applicationset-controller.jsonpatch.yaml
    target:
      name: argocd-applicationset-controller
      kind: Deployment
      group: apps
      version: v1
  - path: argocd-resources.argocd-dex-server.jsonpatch.yaml
    target:
      name: argocd-dex-server
      kind: Deployment
      group: apps
      version: v1
  - path: argocd-resources.argocd-redis.jsonpatch.yaml
    target:
      name: argocd-redis
      kind: Deployment
      group: apps
      version: v1
  - path: argocd-resources.argocd-repo-server.jsonpatch.yaml
    target:
      name: argocd-repo-server
      kind: Deployment
      group: apps
      version: v1
  - path: argocd-resources.argocd-server.jsonpatch.yaml
    target:
      name: argocd-server
      kind: Deployment
      group: apps
      version: v1
