apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.3/manifests/install.yaml
  - https://raw.githubusercontent.com/codefresh-io/argocd-base/v0.1.10/applicationset/kustomization.yaml
