apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/codefresh-io/argo-cd/release-2.1/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/applicationset/master/manifests/install.yaml?ref=2c62537a8e5a # TODO: switch to the next release when available
  - default-rbac.yaml
images:
  - name: quay.io/codefresh/argocd
    newName: quay.io/codefresh/argocd
    newTag: v2.1.11-cap-CR-10341

# will be effective on argo-cd 2.1
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=20s"
      - "accounts.admin=apiKey,login" # need to be able to generate apikey for generic eventsource
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - "server.insecure=true"

patches:
  # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default
