apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csdp-add-cluster.fullname" . }}-secret
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  CSDP_TOKEN: {{ .Values.csdpToken | b64enc | quote }}
