apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csdp-add-cluster.serviceAccount" . }}
  namespace: {{ .Values.systemNamespace | default "kube-system" }}
  labels:
    {{- include "csdp-add-cluster.labels" . | nindent 4 }}
